# Copyright 2024 Ahhhh-man. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

annotations:
  category: DeveloperTools
  licenses: Apache-2.0
apiVersion: v2
appVersion: 1.16.2
description: |
  Event-driven application platform for Kubernetes
home: https://github.com/Ahhhh-man/charts
icon: https://knative.dev/docs/images/logo/rgb/knative-logo-rgb.png
keywords:
  - knative
  - eventing
maintainers:
  - name: Ahhhh-man
    url: https://github.com/Ahhhh-man
name: knative-eventing
sources:
  - https://github.com/Ahhhh-man/charts/charts/knative-eventing
type: application
version: 0.1.2
