# Copyright 2024 Ahhhh-man. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/ahhhh/net-istio
    - url: https://artifacthub.io/packages/helm/ahhhh/kourier
    - url: https://artifacthub.io/packages/helm/ahhhh/net-kourier
apiVersion: v2
appVersion: 1.18.1
description: |
  Knative Serving builds on Kubernetes to support deploying and serving of applications and
  functions as serverless containers
home: https://github.com/Ahhhh-man/charts
icon: https://knative.dev/docs/images/logo/rgb/knative-logo-rgb.png
keywords:
  - knative
  - serving
maintainers:
  - name: Ahhhh-man
    url: https://github.com/Ahhhh-man
name: knative-serving
sources:
  - https://github.com/Ahhhh-man/charts/tree/main/charts/knative-serving
type: application
version: 0.18.1
kubeVersion: '>= 1.31.0-0'
