# Copyright 2024 Ahhhh-man. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

annotations:
  category: DeveloperTools
  licenses: Apache-2.0
apiVersion: v2
appVersion: 1.16.0
description: |
  Knative Serving builds on Kubernetes to support deploying and serving of applications and
  functions as serverless containers.
home: https://github.com/Ahhhh-man/charts
icon: https://knative.dev/docs/images/logo/rgb/knative-logo-rgb.png
keywords:
  - knative
  - serving
maintainers:
  - name: Ahhhh-man
    url: https://github.com/Ahhhh-man
name: knative-serving
sources:
  - https://github.com/Ahhhh-man/charts/charts/knative-serving
type: application
version: 0.1.5
